[package]
name = "doggowarp"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.86"
pixels = "0.13.0"
rayon = "1.10.0"
zune-jpeg = "0.4.11"

[dependencies.winit]
version ="0.30.4"
features = ["rwh_05"]

[profile.dev.package."*"]
opt-level = 3
